name: Android CI
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { lfs: true }

      # JDK 17 d'abord (requis par cmdline-tools 16+)
      - uses: actions/setup-java@v4
        with: { distribution: temurin, java-version: '17', cache: gradle }

      - uses: android-actions/setup-android@v3

      # NDK 22
      - uses: nttld/setup-ndk@v1
        with: { ndk-version: 22.0.7026061, add-to-path: true }

      - name: Accept licenses
        run: yes | sdkmanager --licenses

      - name: Inject keys.xml
        run: |
          mkdir -p app/src/main/res/values
          cat > app/src/main/res/values/keys.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <resources>
            <string name="dji_key">496b0c6af2c99d99a9860d8f</string>
            <string name="google_key">AIzaSyAQm1C-hv_hcJjCeSIW8W7YPQal46Uq31w</string>
          </resources>
          EOF

      - name: Build APK
        run: ./gradlew clean assembleDebug --no-daemon

      - uses: actions/upload-artifact@v4
        with:
          name: rosettadrone-apk
          path: '**/build/outputs/apk/**/*.apk'
